# Generated by Django 2.2.5 on 2020-07-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
